name: zzp-e
on: pull_request
permissions:
  contents: read
jobs:
  call:
    uses: ./.github/workflows/zzrw-e.yml
    with:
      environment: staging
      image: ghcr.io/example/example
      digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
